const cron = require('node-cron');
const { sql, getPool, generateId } = require('../database/db');

class RecurringTaskScheduler {
    constructor() {
        this.job = null;
    }

    start() {
        // Run every hour to check for recurring tasks
        this.job = cron.schedule('0 * * * *', async () => {
            // Silent execution
            await this.processRecurringTasks();
            await this.checkAndNotifyOverdueTasks();
        });

        // Run CometChat full sync every 6 hours
        cron.schedule('0 */6 * * *', async () => {
            // Silent background sync
            try {
                const { syncAllToCometChat } = require('./cometChatService');
                await syncAllToCometChat();
            } catch (err) {
                console.error('Background CometChat sync failed:', err);
            }
        });

        // Run Keepa Seller ASIN auto-discovery every 12 hours
        cron.schedule('0 */12 * * *', async () => {
            console.log('[Keepa] Running scheduled seller ASIN sync...');
            try {
                if (!process.env.KEEPA_API_KEY) {
                    console.log('[Keepa] Skipping: KEEPA_API_KEY not set');
                    return;
                }
                const { syncSellerFromKeepaInternal } = require('../controllers/sellerAsinTrackerController');
                const pool = await getPool();
                const sellersResult = await pool.request().query("SELECT * FROM Sellers WHERE IsActive = 1");
                const sellers = sellersResult.recordset;

                for (const seller of sellers) {
                    try {
                        const r = await syncSellerFromKeepaInternal(seller);
                        if (r.added > 0) {
                            console.log(`[Keepa] ${seller.Name}: +${r.added} new ASINs auto-added`);
                        }
                    } catch (e) {
                        console.error(`[Keepa] Failed for ${seller.Name}:`, e.message);
                    }
                }
                console.log('[Keepa] Scheduled sync complete');
            } catch (err) {
                console.error('[Keepa] Scheduled sync error:', err);
            }
        });

        console.log('Recurring task scheduler started');
    }

    stop() {
        if (this.job) {
            this.job.stop();
            console.log('Recurring task scheduler stopped');
        }
    }

    async processRecurringTasks() {
        try {
            const now = new Date();
            const pool = await getPool();

            // Fetch all Actions where Recurring is enabled and Status is COMPLETED
            const result = await pool.request().query(`
                SELECT * FROM Actions 
                WHERE Status = 'COMPLETED'
            `);

            const actions = result.recordset.filter(a => {
                try {
                    const recurring = JSON.parse(a.Recurring || '{}');
                    if (!recurring.enabled || !recurring.nextOccurrence) return false;
                    return new Date(recurring.nextOccurrence) <= now;
                } catch (e) {
                    return false;
                }
            });

            // Silent creation check

            for (const action of actions) {
                try {
                    const recurring = JSON.parse(action.Recurring || '{}');
                    
                    // Create new instance
                    const newId = generateId();
                    const nextOccurrence = this.calculateNextOccurrence(recurring);
                    
                    const timeTracking = JSON.parse(action.TimeTracking || '{}');
                    const newTimeTracking = JSON.stringify({
                        timeLimit: timeTracking.timeLimit
                    });

                    const newRecurring = JSON.stringify({
                        ...recurring,
                        parentActionId: action.Id
                    });

                    const autoGenerated = JSON.stringify({
                        isAuto: true,
                        source: 'RECURRING',
                        confidence: 100
                    });

                    await pool.request()
                        .input('Id', sql.VarChar, newId)
                        .input('Title', sql.NVarChar, action.Title)
                        .input('Description', sql.NVarChar, action.Description)
                        .input('Type', sql.NVarChar, action.Type)
                        .input('Priority', sql.NVarChar, action.Priority)
                        .input('Status', sql.NVarChar, 'PENDING')
                        .input('Asins', sql.NVarChar, action.Asins)
                        .input('SellerId', sql.VarChar, action.SellerId)
                        .input('AssignedTo', sql.VarChar, action.AssignedTo)
                        .input('CreatedBy', sql.VarChar, action.CreatedBy)
                        .input('TimeTracking', sql.NVarChar, newTimeTracking)
                        .input('Recurring', sql.NVarChar, newRecurring)
                        .input('AutoGenerated', sql.NVarChar, autoGenerated)
                        .query(`
                            INSERT INTO Actions (Id, Title, Description, Type, Priority, Status, Asins, SellerId, AssignedTo, CreatedBy, TimeTracking, Recurring, AutoGenerated, CreatedAt, UpdatedAt)
                            VALUES (@Id, @Title, @Description, @Type, @Priority, @Status, @Asins, @SellerId, @AssignedTo, @CreatedBy, @TimeTracking, @Recurring, @AutoGenerated, GETDATE(), GETDATE())
                        `);

                    console.log(`Created recurring instance for action ${action.Id}: ${newId}`);

                    // Update parent action's next occurrence
                    const updatedRecurring = JSON.stringify({
                        ...recurring,
                        nextOccurrence: nextOccurrence
                    });

                    await pool.request()
                        .input('id', sql.VarChar, action.Id)
                        .input('recurring', sql.NVarChar, updatedRecurring)
                        .query("UPDATE Actions SET Recurring = @recurring, UpdatedAt = GETDATE() WHERE Id = @id");

                    console.log(`Updated next occurrence for action ${action.Id}: ${nextOccurrence}`);
                } catch (error) {
                    console.error(`Failed to create recurring instance for action ${action.Id}:`, error);
                }
            }
        } catch (error) {
            console.error('Error processing recurring tasks:', error);
        }
    }

    calculateNextOccurrence(recurring) {
        if (!recurring.enabled) return null;

        const now = new Date();
        let nextDate = new Date(now);

        switch (recurring.frequency) {
            case 'DAILY':
                nextDate.setDate(nextDate.getDate() + 1);
                break;

            case 'WEEKLY':
                if (recurring.daysOfWeek && recurring.daysOfWeek.length > 0) {
                    const currentDay = now.getDay();
                    const sortedDays = recurring.daysOfWeek.sort((a, b) => a - b);

                    let nextDay = sortedDays.find(day => day > currentDay);
                    if (!nextDay) {
                        nextDay = sortedDays[0];
                        nextDate.setDate(nextDate.getDate() + 7);
                    }

                    const daysToAdd = nextDay - currentDay;
                    nextDate.setDate(nextDate.getDate() + daysToAdd);
                } else {
                    nextDate.setDate(nextDate.getDate() + 7);
                }
                break;

            case 'MONTHLY':
                nextDate.setMonth(nextDate.getMonth() + 1);
                break;
        }

        return nextDate;
    }

    async checkAndNotifyOverdueTasks() {
        try {
            const { sendOverdueReminder } = require('./emailService');
            const now = new Date();
            const pool = await getPool();

            // Find incomplete actions that are overdue
            const result = await pool.request().query(`
                SELECT a.*, u.FirstName, u.LastName, u.Email
                FROM Actions a
                LEFT JOIN Users u ON a.AssignedTo = u.Id
                WHERE a.Status != 'COMPLETED' 
                AND a.DueDate <= GETDATE()
            `);

            const overdueActions = result.recordset;

            for (const action of overdueActions) {
                if (action.Email) {
                    const user = {
                        firstName: action.FirstName,
                        lastName: action.LastName,
                        email: action.Email
                    };
                    await sendOverdueReminder(user, action);
                    console.log(`Sent overdue reminder for action ${action.Id}`);
                }
            }
        } catch (error) {
            console.error('Error checking overdue tasks:', error);
        }
    }

    async triggerNow() {
        console.log('Manually triggering recurring task processing...');
        await this.processRecurringTasks();
    }
}

const scheduler = new RecurringTaskScheduler();
module.exports = scheduler;
