import React, { useState, useEffect, useMemo } from 'react';
import {
  Card, Row, Col, Table, Button, DatePicker, Select,
  Upload, Modal, Typography, Space, Input, Tag, Tooltip, message, Empty, Progress
} from 'antd';
import {
  UploadOutlined, FilterOutlined,
  CalendarOutlined, SearchOutlined, BarChartOutlined, DatabaseOutlined,
  CreditCardOutlined, InfoCircleOutlined
} from '@ant-design/icons';
import {
  TrendingUp, TrendingDown, RefreshCw, ShoppingBag
} from 'lucide-react';
import Chart from 'react-apexcharts';
import { sellerApi, asinApi, gmsApi } from '../services/api';
import { useDateRange } from '../contexts/DateRangeContext';
import { useAuth } from '../contexts/AuthContext';
import dayjs from 'dayjs';
import weekOfYear from 'dayjs/plugin/weekOfYear';
import isoWeek from 'dayjs/plugin/isoWeek';

dayjs.extend(weekOfYear);
dayjs.extend(isoWeek);

const { Title, Text } = Typography;
const { RangePicker } = DatePicker;

// No mock data generated by default
const generateSeedData = () => [];

// Helper to calculate the DoD, WoW, and MoM trend for a given ASIN row
const getAsinTrend = (asinRow, type, gmsData) => {
  let currentVal = 0;
  let previousVal = 0;
  
  if (type === 'month') {
    const months = Object.keys(asinRow.monthlyRev).sort();
    if (months.length < 1) return null;
    const latestMonth = months[months.length - 1];
    currentVal = asinRow.monthlyRev[latestMonth] || 0;
    
    const prevMonthStr = dayjs(latestMonth + '-01').subtract(1, 'month').format('YYYY-MM');
    // Sum from raw data to support previous month if not in current filters
    const prevMonthData = gmsData.filter(d => d.asin === asinRow.asin && d.date.startsWith(prevMonthStr));
    previousVal = prevMonthData.reduce((sum, d) => sum + d.orderedRevenue, 0);
  } else if (type === 'week') {
    const weeks = Object.keys(asinRow.weeklyRev).sort();
    if (weeks.length < 1) return null;
    const latestWeek = weeks[weeks.length - 1];
    currentVal = asinRow.weeklyRev[latestWeek] || 0;
    
    const [year, weekStr] = latestWeek.split('-W');
    const prevWeekDateObj = dayjs().year(parseInt(year)).isoWeek(parseInt(weekStr)).subtract(1, 'week');
    const prevWeekNum = prevWeekDateObj.isoWeek();
    const prevWeekKey = `${prevWeekDateObj.format('YYYY')}-W${String(prevWeekNum).padStart(2, '0')}`;
    
    // Sum from raw data to support previous week
    const prevWeekData = gmsData.filter(d => {
      if (d.asin !== asinRow.asin) return false;
      const itemDate = dayjs(d.date);
      const itemWeekNum = itemDate.isoWeek();
      const itemWeekKey = `${itemDate.format('YYYY')}-W${String(itemWeekNum).padStart(2, '0')}`;
      return itemWeekKey === prevWeekKey;
    });
    previousVal = prevWeekData.reduce((sum, d) => sum + d.orderedRevenue, 0);
  } else if (type === 'day') {
    const days = Object.keys(asinRow.dailyRev).sort();
    if (days.length < 1) return null;
    const latestDay = days[days.length - 1];
    currentVal = asinRow.dailyRev[latestDay] || 0;
    
    const prevDayStr = dayjs(latestDay).subtract(1, 'day').format('YYYY-MM-DD');
    const prevDayData = gmsData.filter(d => d.asin === asinRow.asin && d.date === prevDayStr);
    previousVal = prevDayData.reduce((sum, d) => sum + d.orderedRevenue, 0);
  }
  
  if (!previousVal) return null;
  return ((currentVal - previousVal) / previousVal) * 100;
};

// ═══════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ═══════════════════════════════════════════════════════════════
export default function GmsTrackerPage() {
  const { user: currentUser, isAdmin, isGlobalUser, hasPermission } = useAuth();
  const [gmsData, setGmsData] = useState([]);
  const [isUploadOpen, setIsUploadOpen] = useState(false);
  const [uploadDate, setUploadDate] = useState(dayjs());
  const [selectedBrands, setSelectedBrands] = useState([]);
  const [selectedAsins, setSelectedAsins] = useState([]);
  const { startDate, endDate } = useDateRange();
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedMonths, setExpandedMonths] = useState({});
  const [expandedWeeks, setExpandedWeeks] = useState({});
  const [fileList, setFileList] = useState([]);

  // Database Sellers / Brands
  const [dbSellers, setDbSellers] = useState([]);
  const [dbAsins, setDbAsins] = useState([]);

  // Upload Progress States
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [uploadStatus, setUploadStatus] = useState('');

  // Fetch Brands/Sellers, ASINs & GMS Tracker data from Database
  useEffect(() => {
    const fetchSellers = async () => {
      try {
        const res = await sellerApi.getAll({ limit: 1000 });
        if (res.success && res.data?.sellers) {
          setDbSellers(res.data.sellers);
        }
      } catch (err) {
        console.error('Failed to fetch sellers from db:', err);
      }
    };
    const fetchAsins = async () => {
      try {
        const res = await asinApi.getAllWithoutPagination();
        if (res.success && res.data) {
          setDbAsins(res.data.asins || res.data || []);
        }
      } catch (err) {
        console.error('Failed to fetch ASINs from db:', err);
      }
    };
    const fetchGmsData = async () => {
      try {
        const res = await gmsApi.getAll();
        if (res.success && res.data) {
          setGmsData(res.data);
        }
      } catch (err) {
        console.error('Failed to fetch GMS data from db:', err);
      }
    };
    fetchSellers();
    fetchAsins();
    fetchGmsData();
  }, []);

  const clearAllData = () => {
    Modal.confirm({
      title: 'Are you sure you want to clear all GMS Tracker data?',
      content: 'This will delete all uploaded GMS records permanently from the database.',
      okText: 'Clear Data',
      okType: 'danger',
      cancelText: 'Cancel',
      async onOk() {
        try {
          const res = await gmsApi.clearAll();
          if (res.success) {
            setGmsData([]);
            message.success('GMS Tracker cleared successfully.');
          }
        } catch (err) {
          message.error('Failed to clear GMS data: ' + err.message);
        }
      }
    });
  };

  // Extract unique brands (merged from DB and CSV uploads) and ASINs for filters
  const uniqueBrands = useMemo(() => {
    const dbNames = dbSellers.map(s => s.name).filter(Boolean);
    const dbAsinBrands = dbAsins.map(a => a.brand).filter(Boolean);
    const csvNames = gmsData.map(d => d.brand).filter(Boolean);
    return [...new Set([...dbNames, ...dbAsinBrands, ...csvNames])].sort();
  }, [dbSellers, dbAsins, gmsData]);

  const uniqueAsins = useMemo(() => [...new Set(gmsData.map(d => d.asin))].filter(Boolean).sort(), [gmsData]);

  // Handle CSV file parsing with visual loading stages
  const handleFileUpload = async (file) => {
    setIsUploading(true);
    setUploadProgress(0);
    setUploadStatus('Uploading report to database...');

    try {
      const formattedDate = uploadDate.format('YYYY-MM-DD');
      const res = await gmsApi.upload(file, formattedDate, (percent) => {
        setUploadProgress(Math.min(95, percent));
        if (percent >= 100) {
          setUploadStatus('Processing and ingestion running on server...');
        }
      });

      if (res.success) {
        setUploadProgress(100);
        setUploadStatus('Processing completed successfully!');
        message.success(`Successfully uploaded GMS report: ${res.processed} rows processed, ${res.skipped} skipped.`);
        
        // Reload fresh data from database
        const freshGms = await gmsApi.getAll();
        if (freshGms.success && freshGms.data) {
          setGmsData(freshGms.data);
        }
        
        setTimeout(() => {
          setIsUploadOpen(false);
          setIsUploading(false);
          setFileList([]);
          setUploadProgress(0);
          setUploadStatus('');
        }, 800);
      } else {
        throw new Error(res.error || 'Ingestion failed');
      }
    } catch (err) {
      console.error(err);
      message.error('File upload failed: ' + err.message);
      setIsUploading(false);
      setUploadProgress(0);
      setUploadStatus('');
    }
    return false; // prevent default upload
  };

  // Filter Data
  const filteredData = useMemo(() => {
    return gmsData.filter(item => {
      const itemDate = dayjs(item.date);
      const isWithinDate = (startDate && endDate) 
        ? (itemDate.isSame(dayjs(startDate), 'day') || itemDate.isAfter(dayjs(startDate))) &&
          (itemDate.isSame(dayjs(endDate), 'day') || itemDate.isBefore(dayjs(endDate)))
        : true;
      
      const isBrandMatch = selectedBrands.length > 0 
        ? (selectedBrands.includes(item.brand) || selectedBrands.includes(item.dbBrand)) 
        : true;
      const isAsinMatch = selectedAsins.length > 0 ? selectedAsins.includes(item.asin) : true;
      
      const isSearchMatch = searchQuery
        ? (item.asin && item.asin.toLowerCase().includes(searchQuery.toLowerCase())) ||
          (item.productTitle && item.productTitle.toLowerCase().includes(searchQuery.toLowerCase())) ||
          (item.brand && item.brand.toLowerCase().includes(searchQuery.toLowerCase())) ||
          (item.dbBrand && item.dbBrand.toLowerCase().includes(searchQuery.toLowerCase()))
        : true;

      return isWithinDate && isBrandMatch && isAsinMatch && isSearchMatch;
    });
  }, [gmsData, startDate, endDate, selectedBrands, selectedAsins, searchQuery]);

  // Aggregate Metrics for KPIs
  const kpiMetrics = useMemo(() => {
    let orderedRevenue = 0;
    let orderedUnits = 0;
    let shippedRevenue = 0;
    let shippedCOGS = 0;
    let shippedUnits = 0;
    let customerReturns = 0;

    filteredData.forEach(d => {
      orderedRevenue += d.orderedRevenue;
      orderedUnits += d.orderedUnits;
      shippedRevenue += d.shippedRevenue;
      shippedCOGS += d.shippedCOGS;
      shippedUnits += d.shippedUnits;
      customerReturns += d.customerReturns;
    });

    const profit = shippedRevenue - shippedCOGS;
    const returnRatio = orderedUnits > 0 ? (customerReturns / orderedUnits) * 100 : 0;

    return {
      orderedRevenue,
      orderedUnits,
      shippedRevenue,
      shippedCOGS,
      shippedUnits,
      customerReturns,
      profit,
      returnRatio
    };
  }, [filteredData]);

  // Compute daily trend series for Sparkline charts inside KPI Cards
  const sparklineData = useMemo(() => {
    const sortedDates = [...new Set(filteredData.map(d => d.date))].sort();
    const dateMap = {};
    
    filteredData.forEach(d => {
      if (!dateMap[d.date]) {
        dateMap[d.date] = {
          orderedRevenue: 0,
          orderedUnits: 0,
          shippedRevenue: 0,
          shippedCOGS: 0,
          shippedUnits: 0,
          customerReturns: 0
        };
      }
      dateMap[d.date].orderedRevenue += d.orderedRevenue;
      dateMap[d.date].orderedUnits += d.orderedUnits;
      dateMap[d.date].shippedRevenue += d.shippedRevenue;
      dateMap[d.date].shippedCOGS += d.shippedCOGS;
      dateMap[d.date].shippedUnits += d.shippedUnits;
      dateMap[d.date].customerReturns += d.customerReturns;
    });

    const rev = [];
    const ordUnits = [];
    const netRev = [];
    const shipUnits = [];
    const returns = [];
    const ratio = [];
    const profit = [];

    sortedDates.forEach(date => {
      const day = dateMap[date];
      rev.push(Math.round(day.orderedRevenue));
      ordUnits.push(Math.round(day.orderedUnits));
      netRev.push(Math.round(day.shippedRevenue));
      shipUnits.push(Math.round(day.shippedUnits));
      returns.push(Math.round(day.customerReturns));
      
      const r = day.orderedUnits > 0 ? (day.customerReturns / day.orderedUnits) * 100 : 0;
      ratio.push(parseFloat(r.toFixed(2)));
      
      profit.push(Math.round(day.shippedRevenue - day.shippedCOGS));
    });

    // Fallbacks for empty/single value lists
    const ensureSeries = (arr) => {
      if (arr.length === 0) return [0, 0];
      if (arr.length === 1) return [arr[0], arr[0]];
      return arr;
    };

    return {
      orderedRevenue: ensureSeries(rev),
      orderedUnits: ensureSeries(ordUnits),
      shippedRevenue: ensureSeries(netRev),
      shippedUnits: ensureSeries(shipUnits),
      customerReturns: ensureSeries(returns),
      returnRatio: ensureSeries(ratio),
      profit: ensureSeries(profit)
    };
  }, [filteredData]);

  // Compute period-over-period percentage change for each metric
  const percentageChanges = useMemo(() => {
    const sortedDates = [...new Set(filteredData.map(d => d.date))].sort();
    if (sortedDates.length < 2) {
      return {
        orderedRevenue: 0,
        orderedUnits: 0,
        shippedRevenue: 0,
        shippedUnits: 0,
        customerReturns: 0,
        returnRatio: 0,
        profit: 0
      };
    }

    const mid = Math.floor(sortedDates.length / 2);
    const firstHalf = sortedDates.slice(0, mid);
    const secondHalf = sortedDates.slice(mid);

    const calcChange = (field, isProfit = false) => {
      let firstSum = 0;
      let secondSum = 0;
      filteredData.forEach(d => {
        const val = isProfit ? (d.shippedRevenue - d.shippedCOGS) : d[field];
        if (firstHalf.includes(d.date)) firstSum += val || 0;
        else if (secondHalf.includes(d.date)) secondSum += val || 0;
      });
      if (firstSum === 0) return 0;
      return ((secondSum - firstSum) / firstSum) * 100;
    };

    // Special calculation for return ratio change
    let firstReturns = 0, firstOrdered = 0;
    let secondReturns = 0, secondOrdered = 0;
    filteredData.forEach(d => {
      if (firstHalf.includes(d.date)) {
        firstReturns += d.customerReturns || 0;
        firstOrdered += d.orderedUnits || 0;
      } else {
        secondReturns += d.customerReturns || 0;
        secondOrdered += d.orderedUnits || 0;
      }
    });
    const firstRatio = firstOrdered > 0 ? (firstReturns / firstOrdered) * 100 : 0;
    const secondRatio = secondOrdered > 0 ? (secondReturns / secondOrdered) * 100 : 0;
    const ratioChange = firstRatio === 0 ? 0 : ((secondRatio - firstRatio) / firstRatio) * 100;

    return {
      orderedRevenue: calcChange('orderedRevenue'),
      orderedUnits: calcChange('orderedUnits'),
      shippedRevenue: calcChange('shippedRevenue'),
      shippedUnits: calcChange('shippedUnits'),
      customerReturns: calcChange('customerReturns'),
      returnRatio: ratioChange,
      profit: calcChange('profit', true)
    };
  }, [filteredData]);

  // Dynamic Excel-style horizontal columns and row data grouping by ASIN
  const { tableColumns, tableDataSource } = useMemo(() => {
    if (filteredData.length === 0) {
      return { tableColumns: [], tableDataSource: [] };
    }

    // 1. Group by ASIN to generate rows
    const asinsMap = {};
    filteredData.forEach(d => {
      if (!asinsMap[d.asin]) {
        // Look up brand in database
        const matchedDbAsin = dbAsins.find(a => (a.asinCode || '').toUpperCase() === (d.asin || '').toUpperCase());
        let dbBrandName = '';
        if (matchedDbAsin) {
          if (matchedDbAsin.brand) {
            dbBrandName = matchedDbAsin.brand;
          } else if (matchedDbAsin.sellerName) {
            dbBrandName = matchedDbAsin.sellerName;
          } else if (matchedDbAsin.sellerId) {
            const matchedSeller = dbSellers.find(s => s.id === matchedDbAsin.sellerId);
            if (matchedSeller) {
              dbBrandName = matchedSeller.name;
            }
          }
        }

        asinsMap[d.asin] = {
          key: d.asin,
          asin: d.asin,
          productTitle: matchedDbAsin?.title || d.productTitle,
          dbBrand: d.dbBrand || dbBrandName || '-',
          brand: d.brand || 'Generic',
          storeCode: d.storeCode || matchedDbAsin?.storeCode || 'IN',
          dailyRev: {},
          weeklyRev: {},
          monthlyRev: {}
        };
      }

      const dObj = dayjs(d.date);
      const dateStr = d.date;
      const monthKey = dObj.format('YYYY-MM');
      const weekNum = dObj.isoWeek();
      const weekKey = `${dObj.format('YYYY')}-W${String(weekNum).padStart(2, '0')}`;

      // Day Revenue
      if (!asinsMap[d.asin].dailyRev[dateStr]) asinsMap[d.asin].dailyRev[dateStr] = 0;
      asinsMap[d.asin].dailyRev[dateStr] += d.orderedRevenue;

      // Week Revenue
      if (!asinsMap[d.asin].weeklyRev[weekKey]) asinsMap[d.asin].weeklyRev[weekKey] = 0;
      asinsMap[d.asin].weeklyRev[weekKey] += d.orderedRevenue;

      // Month Revenue
      if (!asinsMap[d.asin].monthlyRev[monthKey]) asinsMap[d.asin].monthlyRev[monthKey] = 0;
      asinsMap[d.asin].monthlyRev[monthKey] += d.orderedRevenue;
    });

    const rows = Object.values(asinsMap);

    // 2. Build column hierarchy
    const fixedCols = [
      {
        title: 'Seller (DB)',
        dataIndex: 'dbBrand',
        key: 'dbBrand',
        width: 140,
        sorter: (a, b) => (a.dbBrand || '').localeCompare(b.dbBrand || '')
      },
      {
        title: 'ASIN',
        dataIndex: 'asin',
        key: 'asin',
        width: 120,
        render: (text) => <Text strong style={{ fontFamily: 'monospace' }}>{text}</Text>,
        sorter: (a, b) => (a.asin || '').localeCompare(b.asin || '')
      },
      {
        title: 'Brand (Sheet)',
        dataIndex: 'brand',
        key: 'brand',
        width: 120,
        sorter: (a, b) => (a.brand || '').localeCompare(b.brand || '')
      },
      {
        title: 'Store Code',
        dataIndex: 'storeCode',
        key: 'storeCode',
        width: 90,
        sorter: (a, b) => (a.storeCode || '').localeCompare(b.storeCode || '')
      }
    ];

    // Gather and sort all unique dates from filteredData
    const dates = [...new Set(filteredData.map(d => d.date))].sort();
    const monthGroups = {};

    dates.forEach(dateStr => {
      const d = dayjs(dateStr);
      const monthKey = d.format('YYYY-MM');
      const monthLabel = d.format('MMMM YYYY');
      const weekNum = d.isoWeek();
      const weekKey = `${d.format('YYYY')}-W${String(weekNum).padStart(2, '0')}`;

      const startOfWeek = d.startOf('isoWeek').format('DD MMM');
      const endOfWeek = d.endOf('isoWeek').format('DD MMM');
      const weekLabel = `Week ${weekNum} (${startOfWeek} - ${endOfWeek})`;

      if (!monthGroups[monthKey]) {
        monthGroups[monthKey] = {
          label: monthLabel,
          key: monthKey,
          weeks: {}
        };
      }

      if (!monthGroups[monthKey].weeks[weekKey]) {
        monthGroups[monthKey].weeks[weekKey] = {
          label: weekLabel,
          key: weekKey,
          days: []
        };
      }

      monthGroups[monthKey].weeks[weekKey].days.push(dateStr);
    });

    // Build nested dynamic Excel columns with collapsible month and week levels
    const dynamicCols = Object.values(monthGroups).map(month => {
      const isMonthExpanded = expandedMonths[month.key] !== false; // default to expanded

      const toggleMonth = (e) => {
        e.stopPropagation();
        setExpandedMonths(prev => ({ ...prev, [month.key]: !isMonthExpanded }));
      };

      const monthTitle = (
        <span 
          style={{ cursor: 'pointer', userSelect: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6 }} 
          onClick={toggleMonth}
        >
          <span style={{ fontSize: 10, color: '#4f46e5', fontWeight: 900 }}>
            {isMonthExpanded ? '▼' : '▶'}
          </span>
          {month.label}
        </span>
      );

      if (!isMonthExpanded) {
        // Collapsed Month: show only Month Total and MoM Trend directly under the Month header
        return {
          title: monthTitle,
          children: [
            {
              title: 'Month Total',
              key: `month-total-${month.key}`,
              align: 'right',
              width: 130,
              render: (_, record) => {
                const rev = record.monthlyRev[month.key] || 0;
                return rev ? <span style={{ fontWeight: 800, color: '#0f172a' }}>₹{rev.toLocaleString('en-IN')}</span> : '-';
              },
              sorter: (a, b) => (a.monthlyRev[month.key] || 0) - (b.monthlyRev[month.key] || 0)
            },
            {
              title: 'MoM Trend',
              key: `mom-trend-${month.key}`,
              align: 'center',
              width: 110,
              render: (_, record) => {
                const trend = getAsinTrend(record, 'month', gmsData);
                if (trend === null) return <span style={{ color: '#94a3b8' }}>-</span>;
                const isUp = trend >= 0;
                return <Tag color={isUp ? 'success' : 'error'} style={{ border: 'none', fontWeight: 700 }}>{isUp ? '▲' : '▼'} {trend.toFixed(1)}%</Tag>;
              },
              sorter: (a, b) => (getAsinTrend(a, 'month', gmsData) || 0) - (getAsinTrend(b, 'month', gmsData) || 0)
            }
          ]
        };
      }

      // Expanded Month: build week sub-columns
      const weekCols = Object.values(month.weeks).map(week => {
        const isWeekExpanded = expandedWeeks[week.key] !== false; // default to expanded

        const toggleWeek = (e) => {
          e.stopPropagation();
          setExpandedWeeks(prev => ({ ...prev, [week.key]: !isWeekExpanded }));
        };

        const weekTitle = (
          <span 
            style={{ cursor: 'pointer', userSelect: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4 }} 
            onClick={toggleWeek}
          >
            <span style={{ fontSize: 9, color: '#4f46e5', fontWeight: 900 }}>
              {isWeekExpanded ? '▼' : '▶'}
            </span>
            {week.label}
          </span>
        );

        if (!isWeekExpanded) {
          // Collapsed Week: show only Week Total and WoW Trend
          return {
            title: weekTitle,
            children: [
              {
                title: 'Week Total',
                key: `week-total-${week.key}`,
                align: 'right',
                width: 120,
                render: (_, record) => {
                  const rev = record.weeklyRev[week.key] || 0;
                  return rev ? <span style={{ fontWeight: 700, color: '#4f46e5' }}>₹{rev.toLocaleString('en-IN')}</span> : '-';
                },
                sorter: (a, b) => (a.weeklyRev[week.key] || 0) - (b.weeklyRev[week.key] || 0)
              },
              {
                title: 'WoW Trend',
                key: `wow-trend-${week.key}`,
                align: 'center',
                width: 110,
                render: (_, record) => {
                  const trend = getAsinTrend(record, 'week', gmsData);
                  if (trend === null) return <span style={{ color: '#94a3b8' }}>-</span>;
                  const isUp = trend >= 0;
                  return <Tag color={isUp ? 'success' : 'error'} style={{ border: 'none', fontWeight: 700 }}>{isUp ? '▲' : '▼'} {trend.toFixed(1)}%</Tag>;
                },
                sorter: (a, b) => (getAsinTrend(a, 'week', gmsData) || 0) - (getAsinTrend(b, 'week', gmsData) || 0)
              }
            ]
          };
        }

        // Expanded Week: show day columns and trends
        const dayCols = week.days.map(dayStr => ({
          title: dayjs(dayStr).format('DD MMM'),
          key: `day-${dayStr}`,
          align: 'right',
          width: 100,
          render: (_, record) => {
            const rev = record.dailyRev[dayStr] || 0;
            return rev ? `₹${rev.toLocaleString('en-IN')}` : '-';
          },
          sorter: (a, b) => (a.dailyRev[dayStr] || 0) - (b.dailyRev[dayStr] || 0)
        }));

        // DoD Trend
        dayCols.push({
          title: 'DoD Trend',
          key: `dod-trend-${week.key}`,
          align: 'center',
          width: 110,
          render: (_, record) => {
            const trend = getAsinTrend(record, 'day', gmsData);
            if (trend === null) return <span style={{ color: '#94a3b8' }}>-</span>;
            const isUp = trend >= 0;
            return <Tag color={isUp ? 'success' : 'error'} style={{ border: 'none', fontWeight: 700 }}>{isUp ? '▲' : '▼'} {trend.toFixed(1)}%</Tag>;
          },
          sorter: (a, b) => (getAsinTrend(a, 'day', gmsData) || 0) - (getAsinTrend(b, 'day', gmsData) || 0)
        });

        // Week Total
        dayCols.push({
          title: 'Week Total',
          key: `week-total-${week.key}`,
          align: 'right',
          width: 120,
          render: (_, record) => {
            const rev = record.weeklyRev[week.key] || 0;
            return rev ? <span style={{ fontWeight: 700, color: '#4f46e5' }}>₹{rev.toLocaleString('en-IN')}</span> : '-';
          },
          sorter: (a, b) => (a.weeklyRev[week.key] || 0) - (b.weeklyRev[week.key] || 0)
        });

        // WoW Trend
        dayCols.push({
          title: 'WoW Trend',
          key: `wow-trend-${week.key}`,
          align: 'center',
          width: 110,
          render: (_, record) => {
            const trend = getAsinTrend(record, 'week', gmsData);
            if (trend === null) return <span style={{ color: '#94a3b8' }}>-</span>;
            const isUp = trend >= 0;
            return <Tag color={isUp ? 'success' : 'error'} style={{ border: 'none', fontWeight: 700 }}>{isUp ? '▲' : '▼'} {trend.toFixed(1)}%</Tag>;
          },
          sorter: (a, b) => (getAsinTrend(a, 'week', gmsData) || 0) - (getAsinTrend(b, 'week', gmsData) || 0)
        });

        return {
          title: weekTitle,
          children: dayCols
        };
      });

      // Month Total
      weekCols.push({
        title: 'Month Total',
        key: `month-total-${month.key}`,
        align: 'right',
        width: 130,
        render: (_, record) => {
          const rev = record.monthlyRev[month.key] || 0;
          return rev ? <span style={{ fontWeight: 800, color: '#0f172a' }}>₹{rev.toLocaleString('en-IN')}</span> : '-';
        },
        sorter: (a, b) => (a.monthlyRev[month.key] || 0) - (b.monthlyRev[month.key] || 0)
      });

      // MoM Trend
      weekCols.push({
        title: 'MoM Trend',
        key: `mom-trend-${month.key}`,
        align: 'center',
        width: 110,
        render: (_, record) => {
          const trend = getAsinTrend(record, 'month', gmsData);
          if (trend === null) return <span style={{ color: '#94a3b8' }}>-</span>;
          const isUp = trend >= 0;
          return <Tag color={isUp ? 'success' : 'error'} style={{ border: 'none', fontWeight: 700 }}>{isUp ? '▲' : '▼'} {trend.toFixed(1)}%</Tag>;
        },
        sorter: (a, b) => (getAsinTrend(a, 'month', gmsData) || 0) - (getAsinTrend(b, 'month', gmsData) || 0)
      });

      return {
        title: monthTitle,
        children: weekCols
      };
    });

    return {
      tableColumns: [...fixedCols, ...dynamicCols],
      tableDataSource: rows
    };
  }, [filteredData, gmsData, dbAsins, dbSellers, expandedMonths, expandedWeeks]);

  // Chart configuration
  const chartSeries = useMemo(() => {
    const dailyData = {};
    filteredData.forEach(d => {
      if (!dailyData[d.date]) dailyData[d.date] = 0;
      dailyData[d.date] += d.orderedRevenue;
    });

    // Round values to integers
    Object.keys(dailyData).forEach(k => {
      dailyData[k] = Math.round(dailyData[k]);
    });

    const sortedDates = Object.keys(dailyData).sort();
    return {
      options: {
        chart: {
          id: 'gms-revenue-trend',
          toolbar: { show: false },
          sparkline: { enabled: false }
        },
        colors: ['#0f172a'],
        stroke: { curve: 'smooth', width: 3 },
        xaxis: {
          categories: sortedDates.map(d => dayjs(d).format('DD MMM')),
          labels: { style: { colors: '#64748b', fontSize: '10px' } }
        },
        yaxis: {
          labels: {
            formatter: (val) => `₹${val >= 100000 ? (val / 100000).toFixed(1) + 'L' : val >= 1000 ? (val / 1000).toFixed(0) + 'k' : val}`,
            style: { colors: '#64748b' }
          },
          tooltip: {
            enabled: false
          }
        },
        tooltip: {
          y: {
            formatter: (val) => `₹${Math.round(val).toLocaleString('en-IN')}`
          }
        },
        fill: {
          type: 'gradient',
          gradient: {
            shadeIntensity: 1,
            opacityFrom: 0.45,
            opacityTo: 0.05,
            stops: [0, 100]
          }
        },
        grid: {
          borderColor: '#f1f5f9',
          strokeDashArray: 4
        }
      },
      series: [
        {
          name: 'Ordered Revenue',
          data: sortedDates.map(d => dailyData[d])
        }
      ]
    };
  }, [filteredData]);

  return (
    <div style={{ padding: '8px 12px', background: '#f8fafc', minHeight: 'calc(100vh - 46px)' }}>
      {/* Dynamic Modern CSS Styles */}
      <style>{`
        /* Tighten Table Cell Padding */
        .gms-tracker-table .ant-table-thead > tr > th {
          padding: 6px 8px !important;
          background: #f1f5f9 !important;
          font-weight: 700 !important;
          color: #334155 !important;
          font-size: 11px !important;
          border-bottom: 1px solid #cbd5e1 !important;
        }
        .gms-tracker-table .ant-table-tbody > tr > td {
          padding: 4px 8px !important;
          font-size: 11px !important;
          border-bottom: 1px solid #e2e8f0 !important;
        }
        .gms-tracker-table .ant-table-container {
          border: 1px solid #cbd5e1 !important;
          border-radius: 6px !important;
        }
        /* Custom Scrollbar for Spreadsheet Table */
        .gms-tracker-table .ant-table-body::-webkit-scrollbar {
          height: 6px;
          width: 6px;
        }
        .gms-tracker-table .ant-table-body::-webkit-scrollbar-thumb {
          background: #cbd5e1;
          border-radius: 3px;
        }
        .gms-tracker-table .ant-table-body::-webkit-scrollbar-track {
          background: #f8fafc;
        }
        /* KPI Cards Styling */
        .gms-kpi-card {
          transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1) !important;
          box-shadow: 0 1px 2px rgba(0, 0, 0, 0.02) !important;
          border: 1px solid #e2e8f0 !important;
        }
        .gms-kpi-card:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05) !important;
          border-color: #cbd5e1 !important;
        }
        .kpi-ord-rev { border-left: 3px solid #6366f1 !important; }
        .kpi-ord-units { border-left: 3px solid #3b82f6 !important; }
        .kpi-ship-rev { border-left: 3px solid #10b981 !important; }
        .kpi-ship-units { border-left: 3px solid #06b6d4 !important; }
        .kpi-returns { border-left: 3px solid #ef4444 !important; }
        .kpi-return-ratio { border-left: 3px solid #f97316 !important; }
        .kpi-profit { border-left: 3px solid #8b5cf6 !important; }
        
        /* Compact Select/Inputs */
        .gms-compact-filter .ant-select-selector,
        .gms-compact-filter.ant-input-affix-wrapper {
          border-radius: 6px !important;
          border-color: #cbd5e1 !important;
          padding-top: 2px !important;
          padding-bottom: 2px !important;
        }
        .gms-compact-filter .ant-select-selection-placeholder {
          font-size: 12px !important;
          color: #64748b !important;
        }
      `}</style>

      {/* HEADER SECTION */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, flexWrap: 'wrap', gap: 8 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <Title level={4} style={{ margin: 0, color: '#0f172a', fontWeight: 800, fontSize: '1.25rem' }}>GMS Tracker</Title>
            <Tag color="blue" style={{ border: 'none', fontWeight: 700, borderRadius: 4, fontSize: 10 }}>Interactive</Tag>
          </div>
          <Text type="secondary" style={{ fontSize: 10.5, display: 'block', marginTop: 1 }}>
            Spreadsheet-style horizontal matrix tracker mapping Ordered Revenue across ASINs.
          </Text>
        </div>
        <Space size={8}>
          {(isAdmin || isGlobalUser || hasPermission('gms_tracker_import')) && (
            <Button 
              type="primary" 
              icon={<UploadOutlined />} 
              onClick={() => setIsUploadOpen(true)} 
              style={{ background: '#0f172a', borderColor: '#0f172a', borderRadius: 6, fontWeight: 600, height: 32, fontSize: 12 }}
            >
              Upload GMS Data
            </Button>
          )}
        </Space>
      </div>

      {/* COMPACT FILTER PANEL */}
      <Card 
        style={{ marginBottom: 8, borderRadius: 8, border: '1px solid #e2e8f0', boxShadow: '0 1px 2px rgba(0,0,0,0.01)' }} 
        styles={{ body: { padding: '6px 12px' } }}
      >
        <Row gutter={[8, 8]} align="middle">
          <Col xs={24} sm={8}>
            <Select
              mode="multiple"
              placeholder="All Brands / Sellers"
              value={selectedBrands}
              onChange={setSelectedBrands}
              style={{ width: '100%' }}
              allowClear
              maxTagCount="responsive"
              className="gms-compact-filter"
            >
              {uniqueBrands.map(b => <Select.Option key={b} value={b}>{b}</Select.Option>)}
            </Select>
          </Col>
          <Col xs={24} sm={8}>
            <Select
              mode="multiple"
              placeholder="All ASINs"
              value={selectedAsins}
              onChange={setSelectedAsins}
              style={{ width: '100%' }}
              allowClear
              maxTagCount="responsive"
              className="gms-compact-filter"
            >
              {uniqueAsins.map(a => <Select.Option key={a} value={a}>{a}</Select.Option>)}
            </Select>
          </Col>
          <Col xs={24} sm={8}>
            <Input
              prefix={<SearchOutlined style={{ color: '#94a3b8', fontSize: 12 }} />}
              placeholder="Search by ASIN, Title, Brand..."
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              allowClear
              className="gms-compact-filter"
              style={{ height: 32 }}
            />
          </Col>
        </Row>
      </Card>

      {/* SUMMARY STATS CARDS */}
      <Row gutter={[10, 10]} style={{ marginBottom: 10 }}>
        {/* Card 1: Ordered Revenue */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Ordered Revenue</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#22c55e' }}>
                +{percentageChanges.orderedRevenue.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: '#0f172a', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              ₹{kpiMetrics.orderedRevenue.toLocaleString('en-IN')}
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: ['#22c55e'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Ordered Revenue', data: sparklineData.orderedRevenue }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>

        {/* Card 2: Ordered Units */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Ordered Units</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: percentageChanges.orderedUnits >= 0 ? '#22c55e' : '#ef4444' }}>
                {percentageChanges.orderedUnits >= 0 ? '+' : ''}{percentageChanges.orderedUnits.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: '#0f172a', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              {kpiMetrics.orderedUnits.toLocaleString()}
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: [percentageChanges.orderedUnits >= 0 ? '#22c55e' : '#ef4444'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Ordered Units', data: sparklineData.orderedUnits }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>

        {/* Card 3: Net Revenue (Shipped) */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Net Rev (Shipped)</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: percentageChanges.shippedRevenue >= 0 ? '#22c55e' : '#ef4444' }}>
                {percentageChanges.shippedRevenue >= 0 ? '+' : ''}{percentageChanges.shippedRevenue.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: '#0f172a', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              ₹{kpiMetrics.shippedRevenue.toLocaleString('en-IN')}
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: [percentageChanges.shippedRevenue >= 0 ? '#22c55e' : '#ef4444'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Net Revenue', data: sparklineData.shippedRevenue }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>

        {/* Card 4: Shipped Units */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Shipped Units</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: percentageChanges.shippedUnits >= 0 ? '#22c55e' : '#ef4444' }}>
                {percentageChanges.shippedUnits >= 0 ? '+' : ''}{percentageChanges.shippedUnits.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: '#0f172a', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              {kpiMetrics.shippedUnits.toLocaleString()}
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: [percentageChanges.shippedUnits >= 0 ? '#22c55e' : '#ef4444'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Shipped Units', data: sparklineData.shippedUnits }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>

        {/* Card 5: Customer Returns */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Customer Returns</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: percentageChanges.customerReturns <= 0 ? '#22c55e' : '#ef4444' }}>
                {percentageChanges.customerReturns >= 0 ? '+' : ''}{percentageChanges.customerReturns.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: kpiMetrics.customerReturns > 0 ? '#dc2626' : '#0f172a', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              {kpiMetrics.customerReturns.toLocaleString()}
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: [percentageChanges.customerReturns <= 0 ? '#22c55e' : '#ef4444'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Customer Returns', data: sparklineData.customerReturns }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>

        {/* Card 6: Return Ratio */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Return Ratio</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: percentageChanges.returnRatio <= 0 ? '#22c55e' : '#ef4444' }}>
                {percentageChanges.returnRatio >= 0 ? '+' : ''}{percentageChanges.returnRatio.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: (kpiMetrics.returnRatio || 0) > 10 ? '#dc2626' : '#0f172a', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              {(kpiMetrics.returnRatio || 0).toFixed(2)}%
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: [percentageChanges.returnRatio <= 0 ? '#22c55e' : '#ef4444'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Return Ratio', data: sparklineData.returnRatio }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>

        {/* Card 7: Shipped Profit */}
        <Col xs={24} sm={12} md={6} lg={6} xl={3.4}>
          <Card 
            className="gms-kpi-card" 
            style={{ borderRadius: 8, border: '1px solid #e2e8f0', background: '#ffffff', overflow: 'hidden' }} 
            styles={{ body: { padding: '12px 12px 6px 12px', display: 'flex', flexDirection: 'column', height: '100%' } }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: '#64748b' }}>Shipped Profit</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: percentageChanges.profit >= 0 ? '#22c55e' : '#ef4444' }}>
                {percentageChanges.profit >= 0 ? '+' : ''}{percentageChanges.profit.toFixed(1)}%
              </span>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: kpiMetrics.profit >= 0 ? '#15803d' : '#dc2626', marginBottom: 6, fontFamily: 'system-ui, -apple-system' }}>
              ₹{kpiMetrics.profit.toLocaleString('en-IN')}
            </div>
            <div style={{ marginTop: 'auto', marginBottom: 4 }}>
              <Chart
                options={{
                  chart: { sparkline: { enabled: true }, animations: { enabled: false } },
                  stroke: { curve: 'smooth', width: 1.5 },
                  fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.35, opacityTo: 0.02, stops: [0, 100] } },
                  colors: [percentageChanges.profit >= 0 ? '#22c55e' : '#ef4444'],
                  tooltip: { enabled: false }
                }}
                series={[{ name: 'Shipped Profit', data: sparklineData.profit }]}
                type="area"
                height={38}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid #f1f5f9', paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontSize: 9.5, fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: 2, cursor: 'pointer' }}>
                See more details <span style={{ fontSize: 8 }}>&gt;</span>
              </span>
            </div>
          </Card>
        </Col>
      </Row>

      {/* GRAPH CHART VIEW */}
      {filteredData.length > 0 ? (
        <Card style={{ marginBottom: 8, borderRadius: 8, border: '1px solid #e2e8f0', boxShadow: '0 1px 2px rgba(0,0,0,0.01)' }} styles={{ body: { padding: '8px 12px' } }}>
          <div style={{ marginBottom: 4 }}>
            <Text strong style={{ fontSize: 11, color: '#0f172a' }}>Ordered Revenue Trend Timeline</Text>
          </div>
          <Chart
            options={chartSeries.options}
            series={chartSeries.series}
            type="area"
            height={180}
          />
        </Card>
      ) : null}

      {/* DATA HORIZONTAL GRID */}
      <Card style={{ borderRadius: 8, border: '1px solid #e2e8f0', boxShadow: '0 1px 2px rgba(0,0,0,0.01)' }} styles={{ body: { padding: 0 } }}>
        <div style={{ padding: '8px 12px', borderBottom: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Text strong style={{ fontSize: 11, color: '#0f172a' }}>Spreadsheet Data Matrix</Text>
          <Tooltip title="Horizontal breakdown of Ordered Revenue by Month, Week, and Day.">
            <InfoCircleOutlined style={{ color: '#94a3b8', fontSize: 11 }} />
          </Tooltip>
        </div>
        {tableDataSource.length > 0 ? (
          <Table
            columns={tableColumns}
            dataSource={tableDataSource}
            pagination={{ pageSize: 12, showSizeChanger: true, size: 'small' }}
            size="small"
            scroll={{ x: 'max-content' }}
            bordered
            className="gms-tracker-table"
            style={{ borderRadius: '0 0 8px 8px', overflow: 'hidden' }}
          />
        ) : (
          <div style={{ padding: 30, textAlign: 'center' }}>
            <Empty description="No data loaded. Click 'Upload GMS Data' to upload your report file." />
          </div>
        )}
      </Card>

      {/* FILE UPLOAD MODAL WITH COMPLETE DATE PICKER */}
      <Modal
        title={<span style={{ fontWeight: 800 }}>Upload GMS Report</span>}
        open={isUploadOpen}
        onCancel={() => { if (!isUploading) { setIsUploadOpen(false); setFileList([]); } }}
        footer={null}
        destroyOnClose
        centered
        width={450}
        closable={!isUploading}
        maskClosable={!isUploading}
      >
        {isUploading ? (
          <div style={{ padding: '20px 10px', textAlign: 'center' }}>
            <Progress type="circle" percent={uploadProgress} strokeColor="#0f172a" />
            <div style={{ marginTop: 16, fontSize: 13, fontWeight: 700, color: '#0f172a' }}>
              {uploadStatus}
            </div>
            <div style={{ marginTop: 6, fontSize: 11, color: '#64748b' }}>
              Please do not close this window while processing is running.
            </div>
          </div>
        ) : (
          <div style={{ padding: '4px 0' }}>
            <div style={{ marginBottom: 12 }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: '#475569', marginBottom: 4 }}>
                1. ASSOCIATE DATE / MONTH FOR REPORT
              </div>
              <DatePicker
                value={uploadDate}
                onChange={setUploadDate}
                style={{ width: '100%', borderRadius: 6 }}
                picker="date"
                placeholder="Select date for this sheet"
              />
              <div style={{ fontSize: 10, color: '#64748b', marginTop: 4 }}>
                Assigns the loaded metrics to the chosen date for MoM/WoW/DoD trend comparison.
              </div>
            </div>

            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: '#475569', marginBottom: 4 }}>
                2. SELECT FILE TO PARSE
              </div>
              <Upload.Dragger
                accept=".csv,.xlsx,.xls"
                beforeUpload={handleFileUpload}
                fileList={fileList}
                onChange={({ fileList }) => setFileList(fileList)}
                maxCount={1}
              >
                <p className="ant-upload-drag-icon" style={{ marginBottom: 8 }}>
                  <UploadOutlined style={{ color: '#6366f1', fontSize: 24 }} />
                </p>
                <p className="ant-upload-text" style={{ fontSize: 11, fontWeight: 600, color: '#1e293b' }}>
                  Click or drag GMS CSV/Excel report here
                </p>
                <p className="ant-upload-hint" style={{ fontSize: 10, color: '#64748b', padding: '0 8px' }}>
                  Required headers: ASIN, Product Title, Brand, StoreCode, Ordered Revenue, Ordered Units, Shipped Revenue, Shipped COGS, Shipped Units, Customer Returns
                </p>
              </Upload.Dragger>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <Button onClick={() => { setIsUploadOpen(false); setFileList([]); }} style={{ borderRadius: 6, fontSize: 12, height: 32 }}>
                Cancel
              </Button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
