-- Fix OKR Schema to match migrated service requirements

-- 1. Objectives Table Updates
IF COL_LENGTH('dbo.Objectives', 'StartDate') IS NULL
    ALTER TABLE Objectives ADD StartDate DATETIME2;

IF COL_LENGTH('dbo.Objectives', 'EndDate') IS NULL
    ALTER TABLE Objectives ADD EndDate DATETIME2;

IF COL_LENGTH('dbo.Objectives', 'SellerId') IS NULL
    ALTER TABLE Objectives ADD SellerId VARCHAR(24);

IF COL_LENGTH('dbo.Objectives', 'Type') IS NULL
    ALTER TABLE Objectives ADD Type NVARCHAR(50);

IF COL_LENGTH('dbo.Objectives', 'CreatedBy') IS NULL
    ALTER TABLE Objectives ADD CreatedBy VARCHAR(24);

IF COL_LENGTH('dbo.Objectives', 'AutoGenerateWeekly') IS NULL
    ALTER TABLE Objectives ADD AutoGenerateWeekly BIT DEFAULT 0;

-- Make GoalId nullable as some objectives might be standalone or transitional
ALTER TABLE Objectives ALTER COLUMN GoalId VARCHAR(24) NULL;

-- 2. KeyResults Table Updates
IF COL_LENGTH('dbo.KeyResults', 'MetricType') IS NULL
    ALTER TABLE KeyResults ADD MetricType NVARCHAR(50);

IF COL_LENGTH('dbo.KeyResults', 'ResolvedAsins') IS NULL
    ALTER TABLE KeyResults ADD ResolvedAsins NVARCHAR(MAX); -- JSON

IF COL_LENGTH('dbo.KeyResults', 'AchievementPercent') IS NULL
    ALTER TABLE KeyResults ADD AchievementPercent DECIMAL(18, 4) DEFAULT 0;

IF COL_LENGTH('dbo.KeyResults', 'ProjectedValue') IS NULL
    ALTER TABLE KeyResults ADD ProjectedValue DECIMAL(18, 4) DEFAULT 0;

IF COL_LENGTH('dbo.KeyResults', 'DailyRunRateRequired') IS NULL
    ALTER TABLE KeyResults ADD DailyRunRateRequired DECIMAL(18, 4) DEFAULT 0;

IF COL_LENGTH('dbo.KeyResults', 'HealthStatus') IS NULL
    ALTER TABLE KeyResults ADD HealthStatus NVARCHAR(50) DEFAULT 'ON_TRACK';

-- 3. Actions Table Updates (for better tracking)
IF COL_LENGTH('dbo.Actions', 'IsAIGenerated') IS NULL
    ALTER TABLE Actions ADD IsAIGenerated BIT DEFAULT 0;

IF COL_LENGTH('dbo.Actions', 'AiReasoning') IS NULL
    ALTER TABLE Actions ADD AiReasoning NVARCHAR(MAX);

IF COL_LENGTH('dbo.Actions', 'ResolvedAsins') IS NULL
    ALTER TABLE Actions ADD ResolvedAsins NVARCHAR(MAX); -- JSON

IF COL_LENGTH('dbo.Actions', 'AutoGeneratedSource') IS NULL
    ALTER TABLE Actions ADD AutoGeneratedSource NVARCHAR(100);
