module.exports = {
  colors: {
    bgPage:       '#f4f5f7',
    bgCard:       '#ffffff',
    bgSubtle:     '#fafbfc',
    borderHair:   '#eef0f3',
    borderDef:    '#dcdfe4',
    textPrimary:  '#0d0f14',
    textBody:     '#26292f',
    textSec:      '#5b6470',
    textMuted:    '#8b929e',
    textFaint:    '#b8bcc4',
    linkGray:     '#5b6470',
  },
  typography: {
    fontStack: `'Inter', ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif`,
    monoStack: `'SF Mono', ui-monospace, 'JetBrains Mono', Menlo, Consolas, monospace`,
  },
  layout: {
    width: 640,
    cardPadX: 40,
    cardPadTop: 32,
    cardRadius: 4,
    cardBorder: '1px solid #dcdfe4',
    cardShadow: '0 1px 3px rgba(16,24,40,0.05), 0 4px 12px rgba(16,24,40,0.04)',
    pagePad: '40px 20px',
    headerPadding: '24px 40px 20px',
    sectionPadding: '32px 40px',
  },
  brand: {
    name: 'Brand Central',
    logoUrl: 'https://brandcentral.in/wp-content/uploads/2024/09/logo.png',
    tagline: "India's leading e-commerce accelerator",
    supportEmail: 'developer@brandcentral.in',
    phone: '+91 99883 39144',
    address: '3rd Floor, Vama House, Ring Rd, near Rivaa House, opp. S B Center, Udhana Darwaja, Rustampura, Surat, Gujarat 395002',
    website: 'https://brandcentral.in',
    dashboardUrl: process.env.DASHBOARD_URL || process.env.APP_URL || process.env.FRONTEND_URL || 'https://data.brandcentral.in',
    copyright: '© 2024 Brand Central. All rights reserved.',
  },
};
