import React, { useState, useEffect, useMemo } from 'react';
import { Edit2, Trash2, CheckCircle, Clock, AlertTriangle, Filter, Search, Play, Square, Plus, Sparkles, Loader2, Calendar, AlertCircle, ArrowDown, Minus, ThumbsUp, ThumbsDown, RotateCcw, FileText, RefreshCw, Eye } from 'lucide-react';
import CompletionModal from './CompletionModal';
import ActionDetailModal from './ActionDetailModal';
import Popover from '../common/Popover';
import { Badge } from 'reactstrap';



/* ── Reusable review-remark popover ─────────────────────────────── */
const ReviewRemarkPopover = ({ id, status, comments }) => {
    return (
        <Popover
            trigger="hover"
            hoverDelay={0.5}
            placement="top"
            content={
                <div>
                    <div className={`fw-bold mb-1 ${status === 'REJECTED' ? 'text-danger' : 'text-success'}`} style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                        {status === 'REJECTED' ? '❌ Rejection Remark' : '✅ Approval Remark'}
                    </div>
                    <div style={{ color: '#475569' }}>
                        {comments}
                    </div>
                </div>
            }
        >
            <div className="d-flex align-items-center" style={{ cursor: 'pointer' }}>
                <span
                    className={`small text-truncate d-inline-block ${status === 'REJECTED' ? 'text-danger' : 'text-success'}`}
                    style={{ maxWidth: '150px', fontSize: '11px', textDecoration: 'underline dotted', fontWeight: 600 }}
                >
                    {status === 'REJECTED' && <AlertCircle size={10} className="me-1" />}
                    {comments}
                </span>
            </div>
        </Popover>
    );
};

// Detailed Subtable for Auto-Generated Actions
const AutoGeneratedSubTable = ({ action }) => {
    const getHint = (type) => {
        switch (type) {
            case 'TITLE_OPTIMIZATION': return 'Enhance title to be at least 150 characters with primary keywords.';
            case 'IMAGE_OPTIMIZATION': return 'Upload at least 7 high-quality images including lifestyle and infographics.';
            case 'DESCRIPTION_OPTIMIZATION': return 'Expand product description to >500 characters highlighting key benefits.';
            case 'A_PLUS_CONTENT': return 'Design and upload rich A+ content/EBC modules to improve conversion.';
            case 'GENERAL_OPTIMIZATION': return 'Review all listing elements (Title, Images, Bullet Points) to increase overall LQS.';
            default: return 'Review ASIN performance and optimize listing content.';
        }
    };

    const getReason = (type) => {
        switch (type) {
            case 'TITLE_OPTIMIZATION': return 'Title Length Below Target Threshold';
            case 'IMAGE_OPTIMIZATION': return 'Insufficient Image Count (< 7)';
            case 'DESCRIPTION_OPTIMIZATION': return 'Description Length Too Short';
            case 'A_PLUS_CONTENT': return 'Missing A+ Content Modules';
            case 'GENERAL_OPTIMIZATION': return 'Low Listing Quality Score (LQS)';
            default: return 'Automated System Flag';
        }
    };

    return (
        <div className="p-3" style={{ backgroundColor: '#f8fafc', boxShadow: 'inset 0 4px 6px -4px rgba(0, 0, 0, 0.05)', borderBottom: '1px solid #e2e8f0' }}>
            <h6 className="mb-3 d-flex align-items-center gap-2" style={{ fontSize: '0.85rem', fontWeight: 700, color: '#4f46e5' }}>
                <Sparkles size={14} /> Action Breakdown: {getReason(action.type)}
            </h6>
            <div className="table-responsive bg-white rounded shadow-sm border border-light">
                <table className="table table-sm table-hover mb-0" style={{ fontSize: '0.75rem' }}>
                    <thead style={{ backgroundColor: '#f1f5f9' }}>
                        <tr>
                            <th className="py-2 px-3 fw-bold text-dark border-bottom-0">Target ASIN</th>
                            <th className="py-2 px-3 fw-bold text-dark border-bottom-0">Product Name / SKU</th>
                            <th className="py-2 px-3 fw-bold text-dark border-bottom-0">Trigger Reason</th>
                            <th className="py-2 px-3 fw-bold text-dark border-bottom-0">Optimization Hint</th>
                        </tr>
                    </thead>
                    <tbody>
                        {action.asins?.map((asin, i) => (
                            <tr key={i}>
                                <td className="py-2 px-3 fw-bold align-middle" style={{ width: '15%', color: '#334155' }}>
                                    {asin.asinCode || asin.asin || asin}
                                </td>
                                <td className="py-2 px-3 align-middle" style={{ width: '35%' }}>
                                    {asin.title ? <span className="text-truncate d-inline-block" style={{ maxWidth: '280px', color: '#475569' }}>{asin.title}</span> : <span className="text-muted fst-italic">Fetching Title...</span>}
                                    {asin.sku && <div className="text-muted" style={{ fontSize: '10px' }}>SKU: {asin.sku}</div>}
                                </td>
                                <td className="py-2 px-3 align-middle" style={{ width: '25%' }}>
                                    <span className="badge bg-danger-subtle text-danger border border-danger-subtle">
                                        <AlertTriangle size={10} className="me-1" /> {getReason(action.type)}
                                    </span>
                                </td>
                                <td className="py-2 px-3 align-middle" style={{ width: '25%' }}>
                                    <div className="d-flex align-items-center gap-1 text-success fw-bold">
                                        <CheckCircle size={12} /> {getHint(action.type)}
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

const ActionList = ({
    actions = [],
    objectives = [],
    standaloneActions = [],
    loading,
    activeFilter = 'ALL',
    searchQuery = '',
    currentUser,
    onSearchChange,
    onDelete,
    onEdit,
    onAddAction,
    onAISuggest,
    onStatusChange,
    onStartTask,
    onCompleteTask,
    onSubmitForReview,
    onReviewAction,
    onSyncGoal, // New prop
    onViewAction, // Add missing prop
    viewMode = 'STRATEGIC' // STRATEGIC or OPERATIONS
}) => {
    const [filterStatus, setFilterStatus] = useState('');
    const [filterPriority, setFilterPriority] = useState('');
    const [completionModalOpen, setCompletionModalOpen] = useState(false);
    const [selectedAction, setSelectedAction] = useState(null);
    const [timers, setTimers] = useState({});
    const [expandedRows, setExpandedRows] = useState({});
    const [syncingKRs, setSyncingKRs] = useState({});
    const [isDetailModalOpen, setIsDetailModalOpen] = useState(false);
    const [detailAction, setDetailAction] = useState(null);

    const formatCurrency = (val) => {
        if (!val) return '₹0';
        if (val >= 10000000) return `₹${(val / 10000000).toFixed(2)}Cr`;
        if (val >= 100000) return `₹${(val / 100000).toFixed(2)}L`;
        return `₹${val.toLocaleString()}`;
    };

    const handleSync = async (e, kr) => {
        e.stopPropagation();
        if (!onSyncGoal) return;
        setSyncingKRs(prev => ({ ...prev, [kr._id || kr.id]: true }));
        try {
            await onSyncGoal(kr);
        } finally {
            setSyncingKRs(prev => ({ ...prev, [kr._id || kr.id]: false }));
        }
    };

    const handleViewAction = (e, action, type) => {
        if (e) e.stopPropagation();
        if (onViewAction) {
            onViewAction(action);
            return;
        }
        setDetailAction(action);
        setIsDetailModalOpen(true);
    };

    // Update timers every second for actions in progress
    useEffect(() => {
        const interval = setInterval(() => {
            const newTimers = {};
            actions.forEach(action => {
                const id = action._id || action.id;
                if (action.timeTracking?.startedAt && !action.timeTracking?.completedAt) {
                    const elapsed = Math.floor((new Date() - new Date(action.timeTracking.startedAt)) / 1000 / 60);
                    newTimers[id] = elapsed;
                }
            });
            setTimers(newTimers);
        }, 1000);

        return () => clearInterval(interval);
    }, [actions]);

    const isTaskStarted = (action) => {
        return action.timeTracking?.startedAt && !action.timeTracking?.completedAt;
    };

    const isTaskCompleted = (action) => {
        return action.timeTracking?.completedAt || action.status === 'COMPLETED';
    };

    // Robust Permission Helpers
    const hasAdminPrivileges = (user) => {
        if (!user) return false;
        const rawRole = user.role?.name || user.role?.Name || (typeof user.role === 'string' ? user.role : '') || user.roleId || user.RoleId || '';
        const role = String(rawRole).toLowerCase();
        return ['admin', 'manager', 'administrator', 'superadmin', '699048ca4fcb2d4ffb3091c7'].includes(role);
    };

    const isActuallyAdmin = (user) => {
        if (!user) return false;
        const rawRole = user.role?.name || user.role?.Name || (typeof user.role === 'string' ? user.role : '') || user.roleId || user.RoleId || '';
        const role = String(rawRole).toLowerCase();
        return ['admin', 'administrator', 'superadmin', '699048ca4fcb2d4ffb3091c7'].includes(role);
    };

    const isOwnerOfItem = (item, user) => {
        if (!item || !user) return false;
        const userId = (user._id || user.id)?.toString();
        if (!userId) return false;

        // Check various owner/assignee fields
        const ownerId = (item.owner?._id || item.owner)?.toString();
        const assignedId = (item.assignedTo?._id || item.assignedTo)?.toString();
        const createdById = (item.createdBy?._id || item.createdBy)?.toString();

        return userId === ownerId || userId === assignedId || userId === createdById;
    };

    // Shared Filtering Logic
    const matchesFilters = (action) => {
        if (!action) return false;
        const now = new Date();
        const tomorrow = new Date();
        tomorrow.setDate(now.getDate() + 1);
        tomorrow.setHours(0, 0, 0, 0);

        const title = (action.title || action.Title || '').toLowerCase();
        const description = (action.description || action.Description || '').toLowerCase();
        const status = action.status || action.Status || 'PENDING';
        const priority = action.priority || action.Priority || 'MEDIUM';
        const timeTracking = action.timeTracking || action.TimeTracking || {};

        const matchesSearch = !searchQuery ||
            title.includes(searchQuery.toLowerCase()) ||
            description.includes(searchQuery.toLowerCase());

        if (!matchesSearch) return false;
        if (filterStatus && status !== filterStatus) return false;
        if (filterPriority && priority !== filterPriority) return false;

        // KPI active filters
        if (activeFilter === 'ALL') return true;
        if (activeFilter === 'TODO') return status !== 'COMPLETED';
        if (activeFilter === 'PENDING') return status === 'PENDING';
        if (activeFilter === 'IN_PROGRESS') return status === 'IN_PROGRESS';
        if (activeFilter === 'REVIEW') return status === 'REVIEW';
        if (activeFilter === 'COMPLETED') return status === 'COMPLETED';
        if (activeFilter === 'REJECTED') return status === 'REJECTED';
        if (activeFilter === 'OVERDUE') return timeTracking?.deadline && new Date(timeTracking.deadline) < now && status !== 'COMPLETED';
        if (activeFilter === 'TOMORROW') {
            if (!timeTracking?.deadline) return false;
            const d = new Date(timeTracking.deadline);
            const dayAfter = new Date(tomorrow);
            dayAfter.setDate(tomorrow.getDate() + 1);
            return d >= tomorrow && d < dayAfter && status !== 'COMPLETED';
        }
        if (activeFilter === 'UPCOMING') {
            if (!timeTracking?.deadline) return false;
            const d = new Date(timeTracking.deadline);
            const dayAfter = new Date(tomorrow);
            dayAfter.setDate(tomorrow.getDate() + 1);
            return d >= dayAfter && status !== 'COMPLETED';
        }

        return true;
    };

    // Auto-expand everything if filtering or searching
    useEffect(() => {
        if (activeFilter !== 'ALL' || searchQuery || filterStatus) {
            const newExpanded = {};
            objectives.forEach(obj => {
                newExpanded[obj.id || obj._id] = true;
                (obj.keyResults || []).forEach(kr => {
                    newExpanded[kr.id || kr._id] = true;
                });
            });
            setExpandedRows(newExpanded);
        }
    }, [activeFilter, searchQuery, filterStatus, objectives]);

    const handleStartTask = (action) => {
        if (onStartTask) onStartTask(action);
    };

    const toggleRow = (id) => {
        setExpandedRows(prev => ({ ...prev, [id]: !prev[id] }));
    };

    const getStatusDot = (status) => {
        if (status === 'COMPLETED') return <span className="status-dot status-dot-green"></span>;
        if (status === 'IN_PROGRESS') return <span className="status-dot status-dot-yellow"></span>;
        if (status === 'REVIEW') return <span className="status-dot status-dot-purple"></span>;
        if (status === 'PENDING') return <span className="status-dot status-dot-gray"></span>;
        return <span className="status-dot status-dot-red"></span>;
    };

    const renderPriorityIcon = (priority) => {
        switch (priority) {
            case 'HIGH':
            case 'URGENT':
                return <AlertCircle size={14} className="priority-high" />;
            case 'MEDIUM':
                return <Minus size={14} className="priority-medium" />;
            case 'LOW':
                return <ArrowDown size={14} className="priority-low" />;
            default:
                return null;
        }
    };

    const formatUserName = (user) => {
        if (!user) return null;
        const first = user.firstName || '';
        const last = user.lastName || '';
        return `${first} ${last}`.trim() || user.email?.split('@')[0] || 'User';
    };

    const ChevronIcon = ({ expanded }) => (
        <span className="me-2 text-muted" style={{ cursor: 'pointer', transition: 'transform 0.2s', display: 'inline-block', transform: expanded ? 'rotate(90deg)' : 'rotate(0deg)' }}>
            <Play size={10} fill="currentColor" />
        </span>
    );

    const renderTreeTable = () => {
        const normalizedObjectives = (objectives || []).map(obj => {
            let totalActions = 0;
            let completedActions = 0;
            const krs = obj.keyResults || [];
            krs.forEach(kr => {
                const actions = kr.actions || [];
                totalActions += actions.length;
                completedActions += actions.filter(a => isTaskCompleted(a)).length;
            });
            return {
                ...obj,
                id: obj._id || obj.id,
                stats: {
                    total: totalActions,
                    completed: completedActions,
                    progress: obj.progress || (totalActions > 0 ? Math.round((completedActions / totalActions) * 100) : 0)
                }
            };
        });

        const filteredObjectives = normalizedObjectives.map(obj => {
            const filteredKRs = (obj.keyResults || []).map(kr => {
                const filteredActions = (kr.actions || []).filter(matchesFilters);
                if (filteredActions.length === 0 && (searchQuery || filterStatus || activeFilter !== 'ALL')) return null;
                return { ...kr, actions: filteredActions };
            }).filter(Boolean);

            if (filteredKRs.length === 0 && (obj.keyResults || []).length > 0 && (searchQuery || filterStatus || activeFilter !== 'ALL')) return null;
            return { ...obj, keyResults: filteredKRs };
        }).filter(Boolean);

        const rows = [];
        filteredObjectives.forEach(obj => {
            const objId = obj.id || obj._id;
            rows.push({ type: 'OBJECTIVE', level: 0, id: objId, data: obj });
            if (expandedRows[objId]) {
                (obj.keyResults || []).forEach(kr => {
                    const krId = kr.id || kr._id;
                    rows.push({ type: 'KR', level: 1, id: krId, data: kr, parentId: objId });
                    if (expandedRows[krId]) {
                        (kr.actions || []).forEach(action => {
                            rows.push({ type: 'ACTION', level: 2, id: action.id || action._id, data: action, parentId: krId });
                        });
                    }
                });
            }
        });

        // Inject standalone (auto-generated) actions after objective rows
        const filteredStandalone = standaloneActions.filter(matchesFilters);
        if (filteredStandalone.length > 0) {
            rows.push({ type: 'DIVIDER', id: 'standalone-divider', data: { label: `🤖 Auto-Generated Tasks (${filteredStandalone.length})` } });
            filteredStandalone.forEach(action => {
                rows.push({ type: 'ACTION', level: 0, id: action._id || action.id, data: action, standalone: true });
            });
        }

        return (
            <div className="smartsheet-container mt-4" style={{ overflow: 'auto' }}>
                <table className="smartsheet-table">
                    <thead style={{ position: 'sticky', top: 0, zIndex: 20 }}>
                        <tr>
                            <th className="row-index">#</th>
                            <th style={{ width: '28%' }}>Task / Objective Name</th>
                            <th style={{ width: '18%' }}>Details</th>
                            <th style={{ width: '12%' }}>Type</th>
                            <th className="text-center">Progress</th>
                            <th>Assigned</th>
                            <th className="text-center">Priority</th>
                            <th style={{ width: '15%' }}>Review</th>
                            <th className="text-center">Activity</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows.map((row, index) => {
                            const isExpanded = expandedRows[row.id];
                            const { data, level, type, standalone } = row;

                            // Divider separator between objectives and standalone tasks
                            if (type === 'DIVIDER') {
                                return (
                                    <tr key={row.id} style={{ background: 'var(--color-brand-50)', borderTop: '2px solid var(--color-brand-600)', borderBottom: '1px solid var(--color-brand-200)' }}>
                                        <td colSpan={9} style={{ padding: '8px 16px', fontWeight: 700, color: 'var(--color-brand-600)', fontSize: '0.82rem', letterSpacing: '0.03em' }}>
                                            {data.label}
                                        </td>
                                    </tr>
                                );
                            }

                            return (
                                <React.Fragment key={row.id + '-' + type}>
                                    <tr
                                        className={`row-level-${level} ${type.toLowerCase()}-row`}
                                        onClick={() => type === 'ACTION' && !standalone && toggleRow(row.id)}
                                        style={{ cursor: type === 'ACTION' && !standalone ? 'pointer' : 'default' }}
                                    >
                                        <td className="row-index">{index + 1}</td>
                                        <td style={{ paddingLeft: `${12 + (level * 24)}px` }}>
                                            <div className="d-flex align-items-center">
                                                {(type === 'OBJECTIVE' || type === 'KR' || (type === 'ACTION' && standalone)) && (
                                                    <span onClick={() => toggleRow(row.id)}>
                                                        <ChevronIcon expanded={isExpanded} />
                                                    </span>
                                                )}
                                                {type === 'ACTION' && !standalone && <span className="me-2 opacity-25"><div style={{ width: '10px' }}></div></span>}
                                                <div className="d-flex align-items-center gap-2">
                                                    {type === 'ACTION' && getStatusDot(data.status || data.Status)}
                                                    <div className={`sm-task-title ${type !== 'ACTION' ? 'fw-bold' : ''}`}>
                                                        {type === 'OBJECTIVE' && <span className="badge bg-primary-subtle text-primary border-primary-subtle me-2" style={{ fontSize: '9px' }}>OBJ</span>}
                                                        {type === 'KR' && <span className="badge bg-info-subtle text-info border-info-subtle me-2" style={{ fontSize: '9px' }}>KR</span>}
                                                        {data.title || data.Title || ''}
                                                        {type === 'ACTION' && (
                                                            <>
                                                                {data.scopeType === 'BRAND' && (
                                                                    <span className="badge bg-indigo-subtle text-indigo border border-indigo-subtle ms-2" style={{ fontSize: '9px' }}>
                                                                        BRAND SCOPE
                                                                    </span>
                                                                )}
                                                                {data.aiGenerated && (
                                                                    <span className="ms-2 text-info" title="AI Generated Strategy">
                                                                        <Sparkles size={12} />
                                                                    </span>
                                                                )}
                                                            </>
                                                        )}
                                                        {type === 'ACTION' && (data.asins?.length > 0 || data.Asins?.length > 0) && data.scopeType !== 'BRAND' && (
                                                            <span className="badge bg-light text-dark border ms-1" style={{ fontSize: '9px' }}>
                                                                {(data.asins || data.Asins).length} ASIN{(data.asins || data.Asins).length > 1 ? 's' : ''}
                                                            </span>
                                                        )}
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div className="text-muted small text-truncate" style={{ maxWidth: '200px' }}>
                                                {data.description || data.Description || (type === 'OBJECTIVE' ? 'Strategic Goal' : type === 'KR' ? 'Key Metric' : '--')}
                                            </div>
                                        </td>
                                         <td>
                                            {type === 'ACTION' ? (
                                                <div className="d-flex flex-column gap-1">
                                                    <span className="badge bg-secondary-subtle text-secondary border-secondary-subtle" style={{ fontSize: '10px' }}>
                                                        {data.type?.replace('_', ' ')}
                                                    </span>
                                                    {data.expectedImpact?.value > 0 && (
                                                        <span className="fw-bold text-success" style={{ fontSize: '10px' }}>
                                                            +{data.expectedImpact.value}% {data.expectedImpact.metric}
                                                        </span>
                                                    )}
                                                </div>
                                            ) : '--'}
                                        </td>
                                        <td className="text-center">
                                            {type === 'ACTION' ? (
                                                <span className="small fw-bold" style={{ color: data.status === 'COMPLETED' ? '#198754' : '#6c757d' }}>
                                                    {data.status === 'COMPLETED' ? '100%' : data.status === 'IN_PROGRESS' ? '50%' : '0%'}
                                                </span>
                                            ) : (
                                                <div className="d-flex flex-column align-items-center justify-content-center">
                                                    <div className="d-flex align-items-center gap-2">
                                                        <div className="progress" style={{ height: '4px', width: '40px' }}>
                                                            <div className="progress-bar" style={{ width: `${type === 'OBJECTIVE' ? data.stats.progress : (Math.min(100, Math.round((data.currentValue / data.targetValue) * 100)) || 0)}%` }}></div>
                                                        </div>
                                                        <span className="small fw-bold" style={{ fontSize: '10px' }}>
                                                            {type === 'OBJECTIVE' ? data.stats.progress : (Math.min(100, Math.round((data.currentValue / data.targetValue) * 100)) || 0)}%
                                                        </span>
                                                        {type === 'KR' && data.metric === 'GMS' && (
                                                            <button
                                                                onClick={(e) => handleSync(e, data)}
                                                                className={`btn btn-sm btn-link p-0 ms-1 ${syncingKRs[data._id || data.id] ? 'fa-spin' : ''}`}
                                                                title="Sync GMS Progress"
                                                                disabled={syncingKRs[data._id || data.id]}
                                                            >
                                                                <RefreshCw size={10} className={syncingKRs[data._id || data.id] ? 'animate-spin' : ''} />
                                                            </button>
                                                        )}
                                                    </div>
                                                    {type === 'KR' && (data.metric === 'GMS' || data.targetValue > 0) && (
                                                        <div className="smallest text-muted mt-1" style={{ fontSize: '9px' }}>
                                                            {data.metric === 'GMS' ? formatCurrency(data.currentValue) : data.currentValue} / {data.metric === 'GMS' ? formatCurrency(data.targetValue) : data.targetValue}
                                                        </div>
                                                    )}
                                                </div>
                                            )}
                                        </td>
                                        <td>
                                            <div className="d-flex align-items-center gap-2">
                                                <div className="avatar-initial bg-light text-dark border rounded-circle" style={{ width: '20px', height: '20px', fontSize: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>
                                                    {(
                                                        data.assignedTo?.firstName ||
                                                        data.owner?.firstName ||
                                                        data.owners?.[0]?.firstName ||
                                                        data.createdBy?.firstName ||
                                                        'U'
                                                    ).charAt(0)}
                                                </div>
                                                <div className="d-flex flex-column">
                                                    <span className="fw-bold" style={{ fontSize: '11px', color: '#374151' }}>
                                                        {formatUserName(data.assignedTo) ||
                                                            formatUserName(data.owner) ||
                                                            (type === 'OBJECTIVE' && data.owners?.length > 0 ? formatUserName(data.owners[0]) : null) ||
                                                            formatUserName(data.createdBy) || 'Unassigned'}
                                                    </span>

                                                    {/* Assigned By logic for Projects/Objectives */}
                                                    {type === 'OBJECTIVE' && data.createdBy && (
                                                        <span className="text-muted" style={{ fontSize: '9px' }}>
                                                            Assigned By {data.createdBy.firstName}
                                                        </span>
                                                    )}

                                                    {/* Creator info for KRs/Actions */}
                                                    {type !== 'OBJECTIVE' && data.createdBy && (
                                                        <span className="text-muted" style={{ fontSize: '9px' }}>
                                                            by {data.createdBy.firstName}
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                        </td>
                                        <td className="text-center">{renderPriorityIcon(data.priority)}</td>
                                        <td>
                                            {type === 'ACTION' && data.review?.comments ? (
                                                <ReviewRemarkPopover
                                                    id={data._id}
                                                    status={data.review.status}
                                                    comments={data.review.comments}
                                                />
                                            ) : (
                                                <span className="text-muted smallest">--</span>
                                            )}
                                        </td>
                                        <td className="text-center">
                                            <div className="d-flex gap-2 justify-content-center">
                                                {type === 'ACTION' ? (
                                                    <>
                                                        <div className="d-flex align-items-center justify-content-center gap-1">
                                                            <button
                                                                onClick={(e) => handleViewAction(e, data, 'ACTION')}
                                                                className="btn btn-sm btn-light p-1 border shadow-sm"
                                                                title="View Task Details"
                                                            >
                                                                <Eye size={12} />
                                                            </button>
                                                            {(isOwnerOfItem(data, currentUser) || hasAdminPrivileges(currentUser)) && (
                                                                <>
                                                                    {!isTaskCompleted(data) && !isTaskStarted(data) && data.status !== 'REVIEW' && (
                                                                        <button
                                                                            onClick={(e) => { e.stopPropagation(); handleStartTask(data); }}
                                                                            className="btn btn-sm btn-primary p-1 shadow-sm"
                                                                            title="Start Task"
                                                                        >
                                                                            <Play size={12} fill="currentColor" />
                                                                        </button>
                                                                    )}
                                                                    {!isTaskCompleted(data) && isTaskStarted(data) && data.status === 'IN_PROGRESS' && (
                                                                        <button
                                                                            onClick={(e) => { e.stopPropagation(); onSubmitForReview(data); }}
                                                                            className="btn btn-sm btn-success p-1 shadow-sm"
                                                                            title="Stop & Submit"
                                                                        >
                                                                            <Square size={12} fill="currentColor" />
                                                                        </button>
                                                                    )}
                                                                </>
                                                            )}
                                                        </div>
                                                        {data.status === 'REVIEW' && hasAdminPrivileges(currentUser) && (
                                                            <div className="d-flex gap-2">
                                                                <button
                                                                    onClick={(e) => { e.stopPropagation(); onReviewAction(data); }}
                                                                    className="btn btn-sm btn-link p-0 text-success"
                                                                    title="Review Approval"
                                                                >
                                                                    <ThumbsUp size={14} />
                                                                </button>
                                                                <button
                                                                    onClick={(e) => { e.stopPropagation(); onReviewAction(data); }}
                                                                    className="btn btn-sm btn-link p-0 text-danger"
                                                                    title="Review Rejection"
                                                                >
                                                                    <ThumbsDown size={14} />
                                                                </button>
                                                            </div>
                                                        )}
                                                        {(isOwnerOfItem(data, currentUser) || hasAdminPrivileges(currentUser)) && (
                                                            <button onClick={(e) => { e.stopPropagation(); onEdit(data, 'ACTION'); }} className="btn btn-sm btn-link p-0 text-muted" title="Edit Task"><Edit2 size={14} /></button>
                                                        )}
                                                        {hasAdminPrivileges(currentUser) && (
                                                            <button onClick={(e) => { e.stopPropagation(); onDelete && onDelete(data._id || data.id, 'ACTION'); }} className="btn btn-sm btn-link p-0 text-danger" title="Delete Task"><Trash2 size={14} /></button>
                                                        )}
                                                    </>
                                                ) : (
                                                    <div className="d-flex gap-2 justify-content-center align-items-center">
                                                        <button
                                                            onClick={(e) => handleViewAction(e, data, type)}
                                                            className="btn btn-sm btn-light p-1 border shadow-sm"
                                                            title={`View ${type} Details`}
                                                        >
                                                            <Eye size={12} />
                                                        </button>
                                                        {(isOwnerOfItem(data, currentUser) || hasAdminPrivileges(currentUser)) && (
                                                            <button onClick={(e) => { e.stopPropagation(); onEdit(data, type); }} className="btn btn-sm btn-link p-0 text-muted" title={`Edit ${type}`}><Edit2 size={14} /></button>
                                                        )}
                                                        {hasAdminPrivileges(currentUser) && (
                                                            <button onClick={(e) => { e.stopPropagation(); onDelete && onDelete(data._id || data.id, type); }} className="btn btn-sm btn-link p-0 text-danger" title={`Delete ${type}`}><Trash2 size={14} /></button>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                        </td>
                                    </tr>
                                    {/* Auto-Generated Detailed Sub-table */}
                                    {isExpanded && type === 'ACTION' && standalone && (
                                        <tr>
                                            <td colSpan={9} className="p-0 border-0">
                                                <AutoGeneratedSubTable action={data} />
                                            </td>
                                        </tr>
                                    )}
                                    {/* Row Expansion Details for non-standalone actions */}
                                    {isExpanded && type === 'ACTION' && !standalone && (
                                        <tr>
                                            <td colSpan={9} className="p-0 border-0">
                                                <div style={{ padding: '16px', backgroundColor: 'var(--color-surface-1)', borderBottom: '1px solid var(--color-border)' }}>
                                                    <div className="row g-3">
                                                        {/* Full Description */}
                                                         <div className="col-12">
                                                            <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--color-text-muted)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Description</div>
                                                            <div style={{ fontSize: '13px', color: 'var(--color-text-secondary)' }}>
                                                                {data.description || 'No description provided'}
                                                            </div>
                                                            {(data.aiReason || data.aiReasoning) && (
                                                                <div className="mt-2 p-2 rounded" style={{ backgroundColor: '#F0F9FF', border: '1px solid #BAE6FD', fontSize: '12px' }}>
                                                                    <div className="fw-bold text-info mb-1"><Sparkles size={12} className="me-1"/> AI STRATEGIC REASONING</div>
                                                                    <div className="text-zinc-700 italic">"{data.aiReason || data.aiReasoning}"</div>
                                                                </div>
                                                            )}
                                                        </div>
                                                        {/* Seller & ASINs */}
                                                        <div className="col-md-6">
                                                            <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--color-text-muted)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Seller & ASINs</div>
                                                            <div style={{ fontSize: '13px' }}>
                                                                <span style={{ fontWeight: 500, color: 'var(--color-text-primary)' }}>{data.sellerId?.name || 'Unassigned'}</span>
                                                                {data.asins?.length > 0 && (
                                                                    <div className="d-flex flex-wrap gap-1 mt-1">
                                                                        {data.asins.map((asin, i) => (
                                                                            <span key={i} className="badge bg-light text-dark border" style={{ fontSize: '10px' }}>
                                                                                {asin.asinCode || asin.asin || asin}
                                                                            </span>
                                                                        ))}
                                                                    </div>
                                                                )}
                                                            </div>
                                                        </div>
                                                        {/* Timeline */}
                                                        <div className="col-md-6">
                                                            <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--color-text-muted)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Timeline</div>
                                                            <div style={{ fontSize: '13px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                                                {data.timeTracking?.startDate ? (
                                                                    <>
                                                                        <span style={{ color: 'var(--color-text-primary)' }}>
                                                                            {new Date(data.timeTracking.startDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}
                                                                        </span>
                                                                        <span style={{ color: 'var(--color-text-muted)' }}>→</span>
                                                                        <span style={{ color: data.timeTracking.deadline && new Date(data.timeTracking.deadline) < new Date() ? 'var(--color-danger-600)' : 'var(--color-text-primary)' }}>
                                                                            {data.timeTracking.deadline ? new Date(data.timeTracking.deadline).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'No deadline'}
                                                                        </span>
                                                                    </>
                                                                ) : (
                                                                    <span style={{ color: 'var(--color-text-muted)' }}>No timeline set</span>
                                                                )}
                                                            </div>
                                                        </div>
                                                        {/* Last Activity */}
                                                        <div className="col-12">
                                                            <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--color-text-muted)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Last Activity</div>
                                                            <div style={{ fontSize: '12px', color: 'var(--color-text-secondary)' }}>
                                                                {data.updatedAt ? (
                                                                    <span>Updated {new Date(data.updatedAt).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
                                                                ) : (
                                                                    <span className="text-muted">No activity recorded</span>
                                                                )}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    )}
                                </React.Fragment>
                            );
                        })}
                    </tbody>
                </table>
                {filteredObjectives.length === 0 && (
                    <div className="text-center py-5 text-muted">
                        <Filter className="mb-2 opacity-25" size={32} />
                        <div style={{ fontSize: '13px' }}>No items found matching the current filters.</div>
                    </div>
                )}
            </div>
        );
    };

    const renderFlatTable = () => {
        let flattenedActions = [];
        objectives.forEach(obj => {
            (obj.keyResults || []).forEach(kr => {
                (kr.actions || []).forEach(action => {
                    flattenedActions.push({ ...action, objectiveTitle: obj.title, krTitle: kr.title });
                });
            });
        });

        const filtered = flattenedActions.filter(matchesFilters);

        return (
            <div className="smartsheet-container mt-4">
                <table className="smartsheet-table">
                    <thead>
                        <tr>
                            <th className="row-index">#</th>
                            <th style={{ width: '30%' }}>Task Name</th>
                            <th style={{ width: '15%' }}>Context</th>
                            <th style={{ width: '10%' }}>Status</th>
                            <th style={{ width: '10%' }}>Seller</th>
                            <th style={{ width: '10%' }}>ASINs</th>
                            <th className="text-center">Timer</th>
                            <th style={{ width: '12%' }}>Assignee</th>
                            <th className="text-center">Priority</th>
                            <th style={{ width: '15%' }}>Review</th>
                            <th className="text-center">Activity</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filtered.map((action, index) => (
                            <tr key={action._id || action.id}>
                                <td className="row-index">{index + 1}</td>
                                <td>
                                    <div className="fw-bold">{action.title || action.Title}</div>
                                    <div className="text-muted smallest text-truncate">{action.description || action.Description}</div>
                                </td>
                                <td>
                                    <div className="smallest text-primary fw-bold text-uppercase">{action.objectiveTitle}</div>
                                    <div className="smallest text-muted">{action.krTitle}</div>
                                </td>
                                <td>
                                    <span className={`badge ${(action.status || action.Status) === 'COMPLETED' ? 'bg-success-subtle text-success' :
                                        (action.status || action.Status) === 'IN_PROGRESS' ? 'bg-primary-subtle text-primary' :
                                            (action.status || action.Status) === 'REVIEW' ? 'bg-info-subtle text-info' :
                                                'bg-warning-subtle text-warning-emphasis'
                                        }`} style={{ fontSize: '10px' }}>
                                        {(action.status || action.Status)?.replace('_', ' ')}
                                    </span>
                                </td>
                                <td className="small text-muted">{action.sellerId?.name || '--'}</td>
                                <td>
                                    <div className="d-flex flex-wrap gap-1">
                                        {action.asins?.slice(0, 2).map((asin, i) => (
                                            <span key={i} className="badge bg-light text-dark border" style={{ fontSize: '9px' }}>
                                                {asin.asinCode || asin.asin || asin}
                                            </span>
                                        ))}
                                        {action.asins?.length > 2 && <span className="smallest text-muted">+{action.asins.length - 2}</span>}
                                    </div>
                                </td>
                                <td className="text-center">
                                    {isTaskStarted(action) ? `${timers[action._id || action.id] || 0}m` : '--'}
                                </td>
                                <td>
                                    <div className="d-flex align-items-center gap-2">
                                        <div className="avatar-initial bg-light text-dark border rounded-circle" style={{ width: '18px', height: '18px', fontSize: '9px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                            {(action.assignedTo?.firstName || action.createdBy?.firstName || 'U').charAt(0)}
                                        </div>
                                        <div className="d-flex flex-column">
                                            <span className="small fw-bold" style={{ fontSize: '10px', color: '#4b5563' }}>
                                                {formatUserName(action.assignedTo) || 'Unassigned'}
                                            </span>
                                            {action.createdBy && action.assignedTo?._id !== action.createdBy?._id && (
                                                <span className="text-muted" style={{ fontSize: '8px' }}>
                                                    by {action.createdBy.firstName}
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </td>
                                <td className="text-center">{renderPriorityIcon(action.priority)}</td>
                                <td>
                                    {action.review?.comments ? (
                                        <ReviewRemarkPopover
                                            id={action._id}
                                            status={action.review.status}
                                            comments={action.review.comments}
                                        />
                                    ) : (
                                        <span className="text-muted smallest">--</span>
                                    )}
                                </td>
                                <td className="text-center">
                                    <div className="d-flex gap-2 justify-content-center">
                                        {(isOwnerOfItem(action, currentUser) || hasAdminPrivileges(currentUser)) && (
                                            <>
                                                {!isTaskCompleted(action) && !isTaskStarted(action) && action.status !== 'REVIEW' && (
                                                    <button onClick={(e) => { e.stopPropagation(); handleStartTask(action); }} className="btn btn-sm btn-link p-0 text-primary" title="Start Task"><Play size={14} /></button>
                                                )}
                                                {!isTaskCompleted(action) && isTaskStarted(action) && action.status === 'IN_PROGRESS' && (
                                                    <button onClick={(e) => { e.stopPropagation(); onSubmitForReview(action); }} className="btn btn-sm btn-link p-0 text-info" title="Submit for Review"><FileText size={14} /></button>
                                                )}
                                            </>
                                        )}
                                        {action.status === 'REVIEW' && isActuallyAdmin(currentUser) && (
                                            <div className="d-flex gap-2">
                                                <button
                                                    onClick={(e) => { e.stopPropagation(); onReviewAction(action); }}
                                                    className="btn btn-sm btn-link p-0 text-success"
                                                    title="Review Approval"
                                                >
                                                    <ThumbsUp size={14} />
                                                </button>
                                                <button
                                                    onClick={(e) => { e.stopPropagation(); onReviewAction(action); }}
                                                    className="btn btn-sm btn-link p-0 text-danger"
                                                    title="Review Rejection"
                                                >
                                                    <ThumbsDown size={14} />
                                                </button>
                                            </div>
                                        )}
                                        {(isOwnerOfItem(action, currentUser) || hasAdminPrivileges(currentUser)) && (
                                            <button onClick={(e) => { e.stopPropagation(); onEdit(action, 'ACTION'); }} className="btn btn-sm btn-link p-0 text-muted" title="Edit Task"><Edit2 size={14} /></button>
                                        )}
                                        {hasAdminPrivileges(currentUser) && (
                                            <button onClick={(e) => { e.stopPropagation(); onDelete && onDelete(action._id || action.id, 'ACTION'); }} className="btn btn-sm btn-link p-0 text-danger" title="Delete Task"><Trash2 size={14} /></button>
                                        )}
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {filtered.length === 0 && (
                    <div className="text-center py-5 text-muted">
                        <Filter className="mb-2 opacity-25" size={32} />
                        <div style={{ fontSize: '13px' }}>No tasks found matching the current filters.</div>
                    </div>
                )}
            </div>
        );
    };

    const renderFilters = () => {
        return (
            <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 16, flexWrap: 'wrap' }}>
                <div style={{ fontSize: 11, fontWeight: 750, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                    Refine Registry:
                </div>
                <select
                    value={filterStatus}
                    onChange={(e) => setFilterStatus(e.target.value)}
                    className="form-select border shadow-sm bg-white"
                    style={{ borderRadius: '8px', height: '32px', width: '150px', fontSize: '11px', fontWeight: 600, color: '#334155', padding: '2px 8px' }}
                >
                    <option value="">All Statuses</option>
                    <option value="PENDING">Pending</option>
                    <option value="IN_PROGRESS">In Progress</option>
                    <option value="REVIEW">Needs Review</option>
                    <option value="COMPLETED">Completed</option>
                </select>
                <select
                    value={filterPriority}
                    onChange={(e) => setFilterPriority(e.target.value)}
                    className="form-select border shadow-sm bg-white"
                    style={{ borderRadius: '8px', height: '32px', width: '150px', fontSize: '11px', fontWeight: 600, color: '#334155', padding: '2px 8px' }}
                >
                    <option value="">All Priorities</option>
                    <option value="LOW">Low</option>
                    <option value="MEDIUM">Medium</option>
                    <option value="HIGH">High</option>
                    <option value="URGENT">Urgent</option>
                </select>
            </div>
        );
    };

    const getPriorityColor = (p) => {
        switch (p) {
            case 'URGENT': return 'text-rose-600 bg-rose-50 border-rose-100';
            case 'HIGH': return 'text-amber-600 bg-amber-50 border-amber-100';
            case 'MEDIUM': return 'text-blue-600 bg-blue-50 border-blue-100';
            default: return 'text-slate-500 bg-slate-50 border-slate-100';
        }
    };
    return (
        <div className="action-list-enhanced py-4">
            {renderFilters()}
            
            <div className="view-transition-container">
                {viewMode === 'STRATEGIC' ? renderTreeTable() : renderFlatTable()}
            </div>

            {/* Modal & Panels */}
            {completionModalOpen && (
                <CompletionModal
                    isOpen={completionModalOpen}
                    action={selectedAction}
                    onClose={() => setCompletionModalOpen(false)}
                    onComplete={onCompleteTask}
                />
            )}
            
            {isDetailModalOpen && (
                <ActionDetailModal
                    isOpen={isDetailModalOpen}
                    onClose={() => {
                        setIsDetailModalOpen(false);
                        setDetailAction(null);
                    }}
                    action={detailAction}
                />
            )}


        </div>
    );
};

export default ActionList;
